from django.core.management.base import BaseCommand
from flashcards.models import CardInfo
from django.conf import settings
import sys
import csv
import os

# from pull_data, generated by Claude bc nice visuals :)
def progress_bar(current, total, width=40):
    filled = int(width * current / total)
    bar = '█' * filled + '░' * (width - filled)
    sys.stdout.write(f'\r|{bar}|')
    sys.stdout.flush()
    if current == total:
        sys.stdout.write('\n')
        sys.stdout.flush()

class Command(BaseCommand): 
    def handle(self, *args, **options):
        updated_cards = []
        sys.stdout.write("\nCreating ID to Audio Dict\n")
        file_path = os.path.join(settings.BASE_DIR, 'flashcards', 'management', 'commands', 'sora.csv')
        id_audio_dict = {}
        with open(file_path, 'r', encoding='utf-8') as file: 
            rows = list(csv.DictReader(file))
            rows = rows[2:] # skip 1st 2 rows bc 2 header rows
            for i, row in enumerate(rows, 1): 
                progress_bar(i, len(rows))
                id_audio_dict[row['ID']] = row['soundSource']

        sys.stdout.write("\nUpdating Audio Paths\n")
        for i, (card_id, audio_path) in enumerate(id_audio_dict.items(), 1):
            progress_bar(i, len(id_audio_dict))
            try:
                card = CardInfo.objects.get(living_dictionaries_id=card_id)
                card.audio_path = audio_path
                card.save()
                updated_cards.append(card)
            # error catching by Copilot
            except CardInfo.DoesNotExist:
                sys.stdout.write(f"\nCard with id {card_id} does not exist.\n")

        # Copilot: delete audio paths for cards not updated
        sys.stdout.write("\nClearing audio paths for cards not in update list\n")
        updated_ids = set(id_audio_dict.keys())
        cards_to_clear = CardInfo.objects.exclude(living_dictionaries_id__in=updated_ids).exclude(audio_path=None)
        total_to_clear = cards_to_clear.count()
        for i, card in enumerate(cards_to_clear, 1):
            progress_bar(i, total_to_clear)
            card.audio_path = None
            card.save()

        cards_updated = len(updated_cards)
        string = "\n" + str(cards_updated) + " paths updated\n"
        sys.stdout.write(string)
            
        