# Generated by Django 5.2.7 on 2026-04-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userstudysettings_daily_new_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudysettings',
            name='first_deck_opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
