# Generated by Django 5.2.7 on 2025-12-27 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_in_lang', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('term', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.IntegerField(default=0)),
                ('see_next', models.DateTimeField(blank=True, null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='flashcards.deck')),
            ],
        ),
    ]
