# Generated by Django 5.2.7 on 2026-01-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_cardinfo_cardtouser_delete_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='cards_to_review',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
