# Generated by Django 5.2.7 on 2026-01-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_deck_cards_to_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='phonetic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
