# Generated by Django 5.2.7 on 2026-03-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0006_remove_deck_cards_to_review_decktouser"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardinfo",
            name="audio_path",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
