# Generated by Django 5.2.7 on 2026-03-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0007_cardinfo_audio_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deck",
            name="name_in_lang",
        ),
        migrations.AlterField(
            model_name="deck",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
