# Generated by Django 5.2.7 on 2026-03-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0008_remove_deck_name_in_lang_alter_deck_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardinfo",
            name="audio_path",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
