# Generated by Django 5.2.7 on 2026-03-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0009_alter_cardinfo_audio_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
