# Generated by Django 5.2.7 on 2026-03-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0010_deck_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeckToUser",
        ),
    ]
