# Generated by Django 5.2.7 on 2026-04-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0011_delete_decktouser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardinfo",
            name="audio_path",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="deck",
            name="slug",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
