# Generated by Django 5.2.7 on 2026-03-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_alter_cardinfo_audio_path_alter_deck_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtouser',
            name='new_introduced_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
