# Generated by Django 5.2.7 on 2026-04-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0013_cardtouser_new_introduced_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='living_dictionaries_id',
            field=models.CharField(default='aaaaaa', max_length=100),
            preserve_default=False,
        ),
    ]
